version: '3'
services: 
  jupyter:
    image: jupyter/datascience-notebook
    restart: always
    environment: 
      JUPYTER_ENABLE_LAB: "yes"
    ports: 
      - 8888:8888
    volumes: 
      - ..:/home/jovyan/work

volumes: 
  notebooks: